# Generated by Django 4.2.7 on 2024-06-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='category_name',
            new_name='category',
        ),
    ]
